// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfPidWatch struct {
	PidStringLen uint64
	PidString    [10]uint8
	_            [6]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleGetdentsEnter *ebpf.ProgramSpec `ebpf:"handle_getdents_enter"`
	HandleGetdentsExit  *ebpf.ProgramSpec `ebpf:"handle_getdents_exit"`
	HandleGetdentsPatch *ebpf.ProgramSpec `ebpf:"handle_getdents_patch"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	MapBuffs     *ebpf.MapSpec `ebpf:"map_buffs"`
	MapBytesRead *ebpf.MapSpec `ebpf:"map_bytes_read"`
	MapProgArray *ebpf.MapSpec `ebpf:"map_prog_array"`
	MapToPatch   *ebpf.MapSpec `ebpf:"map_to_patch"`
	PidMap       *ebpf.MapSpec `ebpf:"pid_map"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	MapBuffs     *ebpf.Map `ebpf:"map_buffs"`
	MapBytesRead *ebpf.Map `ebpf:"map_bytes_read"`
	MapProgArray *ebpf.Map `ebpf:"map_prog_array"`
	MapToPatch   *ebpf.Map `ebpf:"map_to_patch"`
	PidMap       *ebpf.Map `ebpf:"pid_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.MapBuffs,
		m.MapBytesRead,
		m.MapProgArray,
		m.MapToPatch,
		m.PidMap,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleGetdentsEnter *ebpf.Program `ebpf:"handle_getdents_enter"`
	HandleGetdentsExit  *ebpf.Program `ebpf:"handle_getdents_exit"`
	HandleGetdentsPatch *ebpf.Program `ebpf:"handle_getdents_patch"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleGetdentsEnter,
		p.HandleGetdentsExit,
		p.HandleGetdentsPatch,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
